# -*- coding: utf-8 -*-

"""
/***************************************************************************
 GrowthClassifier
                                 A QGIS plugin
 This plugin identifies patch growth type
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-09
        copyright            : (C) 2020 by Mahmood Abdelkader/Ahmed Elseicy
        email                : m.m.i.abdelkader@gmail.com - ahmed.elcc@gmail.com
 ***************************************************************************/
 
"""

__author__ = 'Mahmood Abdelkader/Ahmed Elseicy'
__date__ = '2020-08-09'
__copyright__ = '(C) 2020 by Mahmood Abdelkader/Ahmed Elseicy'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .growth_classifier_algorithm import GrowthClassifierAlgorithm


class GrowthClassifierProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(GrowthClassifierAlgorithm())
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'Vector analysis'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Growth Classifier Algorithm')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
