# -*- coding: utf-8 -*-

"""
/***************************************************************************
 GrowthClassifier
                                 A QGIS plugin
 This plugin identifies patch growth type
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-09
        copyright            : (C) 2020 by Mahmood Abdelkader/Ahmed Elseicy
        email                : m.m.i.abdelkader@gmail.com - ahmed.elcc@gmail.com
 ***************************************************************************/

"""

__author__ = 'Mahmood Abdelkader/Ahmed Elseicy'
__date__ = '2020-08-09'
__copyright__ = '(C) 2020 by Mahmood Abdelkader/Ahmed Elseicy'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .growth_classifier_provider import GrowthClassifierProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class GrowthClassifierPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = GrowthClassifierProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
